In [198]:
import pandas as pd
import numpy as np

In [199]:
news = pd.read_csv('news_y.csv')
fake = pd.read_csv('Fake_y.csv')
true = pd.read_csv('True_y.csv')

In [200]:
news.head()

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",FAKE
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,FAKE
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,REAL
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",FAKE
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,REAL

In [201]:
news['label'] = news['label'].map({'FAKE':0, 'REAL':1}).astype(int)
news.head()

,Unnamed: 0,title,text,label
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",0
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,0
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,1
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",0
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,1

In [202]:
news.rename(columns={'label': 'class'}, inplace=True)
news.head()

,Unnamed: 0,title,text,class
0,8476,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",0
1,10294,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,0
2,3608,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,1
3,10142,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",0
4,875,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,1

In [203]:
news = news.drop(['Unnamed: 0'], axis=1)
news.head()

,title,text,class
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",0
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,0
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,1
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",0
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,1

# SEPARAMOS LOS FAKES AND TRUES DE NEWS DB

In [204]:
fake_news = news[news['class'] == 0]
fake_news

,title,text,class
0,You Can Smell Hillary’s Fear,"Daniel Greenfield, a Shillman Journalism Fello...",0
1,Watch The Exact Moment Paul Ryan Committed Pol...,Google Pinterest Digg Linkedin Reddit Stumbleu...,0
3,Bernie supporters on Twitter erupt in anger ag...,"— Kaydee King (@KaydeeKing) November 9, 2016 T...",0
5,"Tehran, USA","\nI’m not an immigrant, but my grandparents ...",0
6,Girl Horrified At What She Watches Boyfriend D...,"Share This Baylee Luciani (left), Screenshot o...",0
...,...,...,...
6326,DOJ COMPLAINT: Comey Under Fire Over Partisan ...,DOJ COMPLAINT: Comey Under Fire Over Partisan ...,0
6328,Radio Derb Is On The Air–Leonardo And Brazil’s...,,0
6329,Assange claims ‘crazed’ Clinton campaign tried...,Julian Assange has claimed the Hillary Clinton...,0
6331,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,The ‘P’ in PBS Should Stand for ‘Plutocratic’ ...,0
6332,Anti-Trump Protesters Are Tools of the Oligarc...,Anti-Trump Protesters Are Tools of the Oligar...,0

In [205]:
true_news = news[news['class'] == 1]
true_news

,title,text,class
2,Kerry to go to Paris in gesture of sympathy,U.S. Secretary of State John F. Kerry said Mon...,1
4,The Battle of New York: Why This Primary Matters,It's primary day in New York and front-runners...,1
7,‘Britain’s Schindler’ Dies at 106,A Czech stockbroker who saved more than 650 Je...,1
8,Fact check: Trump and Clinton at the 'commande...,Hillary Clinton and Donald Trump made some ina...,1
9,Iran reportedly makes new push for uranium con...,Iranian negotiators reportedly have made a las...,1
...,...,...,...
6324,Alabama Lawmaker: Same-Sex Couples Don’t Deser...,Most conservatives who oppose marriage equalit...,1
6327,GOP Senator David Perdue Jokes About Praying f...,The freshman senator from Georgia quoted scrip...,1
6330,State Department says it can't find emails fro...,The State Department told the Republican Natio...,1
6333,"In Ethiopia, Obama seeks progress on peace, se...","ADDIS ABABA, Ethiopia —President Obama convene...",1
6334,Jeb Bush Is Suddenly Attacking Trump. Here's W...,Jeb Bush Is Suddenly Attacking Trump. Here's W...,1

# MEZCLAMOS

In [206]:
fake_marge = pd.concat([fake_news, fake], axis=0)
fake_marge = fake_marge.sample(frac = 1)
fake_marge.reset_index(inplace = True)
fake_marge.drop(["index"], axis = 1, inplace = True)
fake_marge['class'] = 0
fake_marge

,title,text,class,subject,date
0,Cops In Republican Senate Office Violently As...,A group of disabled Americans protesting the S...,0,News,"June 26, 2017"
1,CNN’s Don Lemon Tries to Downplay Horrific ‘An...,"In case you missed it, CNN anchor Don Lemon we...",0,US_News,"January 6, 2017"
2,Katrina Pierson Just Blamed Hillary Clinton F...,"Following the presidential debate, Donald Trum...",0,News,"September 27, 2016"
3,Chris Matthews Stuns Colleagues By Telling Th...,Ted Cruz is horrible. According to former clas...,0,News,"February 10, 2016"
4,PARKS and REC and JIMMY FALLON Writer Thinks T...,When they go low we go high. Michelle Obam...,0,left-news,"Oct 1, 2017"
...,...,...,...,...,...
29804,WATCH: Republican Strategist BLASTS ‘Lawless’...,Democrats and Republicans don t agree on a lot...,0,News,"July 22, 2017"
29805,BREAKING: Mexico’s President Cancels Visit Wit...,"On March 31, 2015 Sergeant Andrew Tahmooressi ...",0,left-news,"Jan 26, 2017"
29806,Snowflake Trump Makes His Staff Create A Dail...,"A couple of weeks ago, Donald Trump held his f...",0,News,"June 29, 2017"
29807,Eric Trump Gives DUMBEST Defense For His Brot...,The White House is getting really nervous toda...,0,News,"July 11, 2017"
29808,OBAMA PRESSURED U.S. SHOE COMPANY To Keep Thei...,"Of course, putting America first is a totally ...",0,left-news,"Apr 14, 2016"

In [207]:
#fake_marge.drop(["class"], axis = 1, inplace = True)
#fake_marge

In [208]:
true_marge = pd.concat([true_news, true], axis=0)
true_marge = true_marge.sample(frac = 1)
true_marge.reset_index(inplace = True)
true_marge.drop(["index"], axis = 1, inplace = True)
true_marge['class'] = 1
true_marge

,title,text,class,subject,date
0,Energy Secretary Perry cancels Kazakhstan visi...,ALMATY (Reuters) - United States Energy Secret...,1,politicsNews,"August 28, 2017"
1,"Dozens killed, wounded by car bomb in Afghan p...","KABUL (Reuters) - As many as 13 people, includ...",1,worldnews,"August 27, 2017"
2,Moscow to cut dependence on U.S. payment syste...,MOSCOW (Reuters) - Russia will speed up work o...,1,politicsNews,"August 7, 2017"
3,"In Syria, Russia securing position as Assad pr...",BEIRUT (Reuters) - With the map of Syria s con...,1,worldnews,"December 15, 2017"
4,"Coca, trafficking greatest threats to Colombia...",BOGOTA (Reuters) - A peace deal between Colomb...,1,worldnews,"October 13, 2017"
...,...,...,...,...,...
27754,How Tim Scott chose to endorse Marco Rubio for...,"Like a modern day Ben Franklin, Sen. Tim Scott...",1,NaN,NaN
27755,Finnish president says joining NATO would requ...,HELSINKI (Reuters) - Any move by Finland to jo...,1,worldnews,"October 30, 2017"
27756,Factbox: Where key U.S. Republican senators st...,WASHINGTON (Reuters) - U.S. Senate Republicans...,1,politicsNews,"June 22, 2017"
27757,"New York, other states challenge Trump over cl...",WASHINGTON (Reuters) - A coalition of 17 U.S. ...,1,politicsNews,"April 5, 2017"
27758,Philippine drugs board chief quits after contr...,MANILA (Reuters) - The head of the Philippines...,1,worldnews,"November 7, 2017"

In [209]:
fake_tail = fake_marge.tail(50)

In [210]:
true_tail = true_marge.tail(50)

In [211]:
fake_true = pd.concat([true_tail, fake_tail], axis=0)
fake_true = fake_true.sample(frac = 1)
fake_true.reset_index(inplace = True)
fake_true.drop(["index"], axis = 1, inplace = True)
fake_true

,title,text,class,subject,date
0,‘We Caved’,"On a late July day this past summer, a roar fi...",1,NaN,NaN
1,Zimbabwe court postpones U.S. citizen's subver...,HARARE (Reuters) - A Zimbabwean court has post...,1,worldnews,"December 8, 2017"
2,Congress sends White House repeal of broadband...,WASHINGTON (Reuters) - The U.S. House voted on...,1,politicsNews,"March 28, 2017"
3,Poland's stance on migrants unchanged despite ...,"KRYNICA ZDROJ, Poland (Reuters) - Poland will ...",1,worldnews,"September 6, 2017"
4,Putin critic Navalny calls election boycott ra...,MOSCOW (Reuters) - Opposition leader Alexei Na...,1,worldnews,"December 27, 2017"
...,...,...,...,...,...
95,Finnish president says joining NATO would requ...,HELSINKI (Reuters) - Any move by Finland to jo...,1,worldnews,"October 30, 2017"
96,Head of UK's anti-Brexit party appeals for hel...,LONDON (Reuters) - Calling himself a proud sa...,1,worldnews,"September 18, 2017"
97,Hezbollah emerges a winner from Mideast turmoi...,BEIRUT (Reuters) - When Iran declared victory ...,1,worldnews,"November 30, 2017"
98,Say What?! FBI Never Destroyed Laptops of Clin...,0 comments \nThis is just too rich! The FBI ag...,0,NaN,NaN
99,Kansas House fails in attempt to override Medi...,(Reuters) - Lawmakers in Kansas on Monday fail...,1,politicsNews,"April 3, 2017"

In [212]:
fakemarge= fake_marge[:-50]
fakemarge

,title,text,class,subject,date
0,Cops In Republican Senate Office Violently As...,A group of disabled Americans protesting the S...,0,News,"June 26, 2017"
1,CNN’s Don Lemon Tries to Downplay Horrific ‘An...,"In case you missed it, CNN anchor Don Lemon we...",0,US_News,"January 6, 2017"
2,Katrina Pierson Just Blamed Hillary Clinton F...,"Following the presidential debate, Donald Trum...",0,News,"September 27, 2016"
3,Chris Matthews Stuns Colleagues By Telling Th...,Ted Cruz is horrible. According to former clas...,0,News,"February 10, 2016"
4,PARKS and REC and JIMMY FALLON Writer Thinks T...,When they go low we go high. Michelle Obam...,0,left-news,"Oct 1, 2017"
...,...,...,...,...,...
29754,IS ROMNEY SERIOUSLY THINKING ABOUT ENTERING TH...,As if this presidential race couldn t get any ...,0,politics,"Aug 24, 2015"
29755,Episode #159 – SUNDAY WIRE: ‘Tick-Tock USA’ wi...,Episode #159 of SUNDAY WIRE SHOW resumes this...,0,US_News,"November 6, 2016"
29756,GROSS! MADONNA OFFERS UP Sexual Services If Yo...,[Warning: Story contains graphic language]Pop ...,0,politics,"Oct 19, 2016"
29757,House Dem Wants GOP On Record: Stop Gov’t Spe...,"Early next month, the GOP-controlled House of ...",0,News,"August 24, 2017"
29758,Clinton campaign blames FBI director for loss ...,Politics FBI Director James Comey (AFP file ph...,0,NaN,NaN

In [213]:
fakemarge.drop(["class"], axis = 1, inplace = True)

/Users/keijiarostegui/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [214]:
truemerge = true_marge[:-50]
truemerge

,title,text,class,subject,date
0,Energy Secretary Perry cancels Kazakhstan visi...,ALMATY (Reuters) - United States Energy Secret...,1,politicsNews,"August 28, 2017"
1,"Dozens killed, wounded by car bomb in Afghan p...","KABUL (Reuters) - As many as 13 people, includ...",1,worldnews,"August 27, 2017"
2,Moscow to cut dependence on U.S. payment syste...,MOSCOW (Reuters) - Russia will speed up work o...,1,politicsNews,"August 7, 2017"
3,"In Syria, Russia securing position as Assad pr...",BEIRUT (Reuters) - With the map of Syria s con...,1,worldnews,"December 15, 2017"
4,"Coca, trafficking greatest threats to Colombia...",BOGOTA (Reuters) - A peace deal between Colomb...,1,worldnews,"October 13, 2017"
...,...,...,...,...,...
27704,Turkey will take its own security measures aft...,ANKARA (Reuters) - President Tayyip Erdogan on...,1,worldnews,"September 13, 2017"
27705,China's Xi says can thwart Taiwan independence...,BEIJING/TAIPEI (Reuters) - China has the resol...,1,worldnews,"October 18, 2017"
27706,"Trump rejects criticism, vents at news media i...",WASHINGTON (Reuters) - Republican presidential...,1,politicsNews,"July 7, 2016"
27707,Selma 50 years on: John Lewis's recalls the march,Watch live coverage of ceremonies in Selma com...,1,NaN,NaN
27708,Afghan president 'grateful' for Trump's commit...,KABUL (Reuters) - Afghan leader Ashraf Ghani o...,1,politicsNews,"August 22, 2017"

In [215]:
truemerge.drop(["class"], axis = 1, inplace = True)

/Users/keijiarostegui/opt/anaconda3/lib/python3.9/site-packages/pandas/core/frame.py:4906: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

In [221]:
truemerge

,title,text,subject,date
0,Energy Secretary Perry cancels Kazakhstan visi...,ALMATY (Reuters) - United States Energy Secret...,politicsNews,"August 28, 2017"
1,"Dozens killed, wounded by car bomb in Afghan p...","KABUL (Reuters) - As many as 13 people, includ...",worldnews,"August 27, 2017"
2,Moscow to cut dependence on U.S. payment syste...,MOSCOW (Reuters) - Russia will speed up work o...,politicsNews,"August 7, 2017"
3,"In Syria, Russia securing position as Assad pr...",BEIRUT (Reuters) - With the map of Syria s con...,worldnews,"December 15, 2017"
4,"Coca, trafficking greatest threats to Colombia...",BOGOTA (Reuters) - A peace deal between Colomb...,worldnews,"October 13, 2017"
...,...,...,...,...
27704,Turkey will take its own security measures aft...,ANKARA (Reuters) - President Tayyip Erdogan on...,worldnews,"September 13, 2017"
27705,China's Xi says can thwart Taiwan independence...,BEIJING/TAIPEI (Reuters) - China has the resol...,worldnews,"October 18, 2017"
27706,"Trump rejects criticism, vents at news media i...",WASHINGTON (Reuters) - Republican presidential...,politicsNews,"July 7, 2016"
27707,Selma 50 years on: John Lewis's recalls the march,Watch live coverage of ceremonies in Selma com...,NaN,NaN
27708,Afghan president 'grateful' for Trump's commit...,KABUL (Reuters) - Afghan leader Ashraf Ghani o...,politicsNews,"August 22, 2017"

In [216]:
#fake_marge.drop(fake_marge.index[-50:])

In [217]:
#true_marge.drop(true_marge.index[-50:])

In [218]:
fakemarge.to_csv('Fake_estesi.csv', index=False)

In [219]:
truemerge.to_csv('True_estesi.csv', index=False)

In [220]:
fake_true.to_csv('News_test.csv', index=False)